services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - dynamodb
      - pennsievedb
    environment:
      - DYNAMODB_ENDPOINT=http://dynamodb:8000
      - POSTGRES_HOST=pennsievedb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
  dynamodb:
    image: amazon/dynamodb-local
    restart: always

  pennsievedb:
    image: pennsieve/pennsievedb:V20240823134600-seed
    restart: always
