version: '3'

networks:
  api-tests:
    driver: bridge

services:
  # Test Container for running tests locally
  local_tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - $PWD:/go/src/github.com/pennsieve/pennsieve-go-api
    networks:
      - api-tests

  # CI Container for running tests on Jenkins
  ci_tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - DYNAMODB_URL=http://dynamodb-ci:8000
    volumes:
      - $PWD:/go/src/github.com/pennsieve/pennsieve-go-api
    networks:
      - api-tests

