name: Sync OAS to ReadMe
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "Unused"
          replace: "Authorization"
          include: "terraform/upload_service.yml"
      - name: Strip internal endpoints
        uses: mikefarah/yq@master
        with:
          cmd: yq 'del(.paths[][] | select(.x-internal == true)) | del(.paths[] | select(length == 0))' terraform/upload_service.yml > terraform/upload_service_public.yml
      - name: Run `openapi` command 🚀
        uses: readmeio/rdme@v8
        with:
          rdme: openapi terraform/upload_service_public.yml --key=${{ secrets.README_OAS_KEY }} --id=66c5fa89dbe4120025445fd9
